### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Calinou** [WiggleWizard/CubemapInspector#1]
I noticed this project currently has no license attached. Please consider [adding an open source license](https://choosealicense.com/) :slightly_smiling_face:

**Comment by Calinou** [comment]
Bump :slightly_smiling_face: Can you please take a look at it?

**Comment by WiggleWizard** [comment]
Will review this application again (to update for Godot 3.1) and add MIT license

**Comment by WiggleWizard** [comment]
MIT license added
